// prettier-ignore
export const notificationActions = {
  ADD_NOTE: 'ADD_NOTE',
  PROBLEM_FOUND: 'PROBLEM_FOUND', // This is the only single action
  RESOLVE_FOR_CUSTOMER: 'RESOLVE_FOR_CUSTOMER',
  RESOLVE_FOR_CUSTOMER_AND_INBOX_ITEM_CHECKED: 'RESOLVE_FOR_CUSTOMER_AND_INBOX_ITEM_CHECKED', // marks the notification has resolved and the inboxItem as checked
  RESOLVE_FOR_ADMIN: 'RESOLVE_FOR_ADMIN',
  SELECT_SUPPLIER_FOR_INBOX_ITEM: 'SELECT_SUPPLIER_FOR_INBOX_ITEM',
  RERUN_INBOX_ITEM: 'RERUN_INBOX_ITEM',
  RERUN_SUB_ITEM: 'RERUN_SUB_ITEM',
  RERUN_DOC: 'RERUN_DOC',
  ADD_TO_INBOX_BLOCK_LIST: 'ADD_TO_INBOX_BLOCK_LIST',
  SKIP_INBOX_ITEM: 'SKIP_INBOX_ITEM',
  ALLOW_INBOX_ITEM_PROCESSING: 'ALLOW_INBOX_ITEM_PROCESSING',
  SELECT_SUPPLIER_FOR_SUB_ITEM: 'SELECT_SUPPLIER_FOR_SUB_ITEM',
  SKIP_SUB_ITEM: 'SKIP_SUB_ITEM',
  ASSIGN_TO_CUSTOMER: 'ASSIGN_TO_CUSTOMER',
  SUSPECT_PHISHING: 'SUSPECT_PHISHING',
  DELETE_SUB_ITEM_AND_RERUN: 'DELETE_SUB_ITEM_AND_RERUN',
  DELETE_SUB_ITEM_DOCS_AND_RERUN: 'DELETE_SUB_ITEM_DOCS_AND_RERUN',
  DELETE_DOC_AND_RERUN: 'DELETE_DOC_AND_RERUN',
  SKIP_DOC: 'SKIP_DOC',
  SELECT_SUPPLIER_ACCOUNT: 'SELECT_SUPPLIER_ACCOUNT',
  SET_CURRENCY: 'SET_CURRENCY',
  SET_PAYMENT_METHOD: 'SET_PAYMENT_METHOD',
  REPLACE_EXISTING_DOC: 'REPLACE_EXISTING_DOC'
};
