// prettier-ignore
export const permissions = {
  CUSTOMER_OBJECTS_VIEW_CUSTOMER_FIELDS: 'CUSTOMER_OBJECTS_VIEW_CUSTOMER_FIELDS',
  CUSTOMER_OBJECTS_EDIT_CUSTOMER_FIELDS: 'CUSTOMER_OBJECTS_EDIT_CUSTOMER_FIELDS',
  CUSTOMER_OBJECTS_VIEW_ADMIN_FIELDS: 'CUSTOMER_OBJECTS_VIEW_ADMIN_FIELDS',
  CUSTOMER_OBJECTS_EDIT_ADMIN_FIELDS: 'CUSTOMER_OBJECTS_EDIT_ADMIN_FIELDS',
  GLOBAL_SUPPLIER_VIEW_CUSTOMER_FIELDS: 'GLOBAL_SUPPLIER_VIEW_CUSTOMER_FIELDS', // restricted to isParentSupplier=false OR isParentSupplier=true parentType=COMPANY_GROUP
  GLOBAL_SUPPLIER_VIEW_ADMIN_FIELDS: 'GLOBAL_SUPPLIER_VIEW_ADMIN_FIELDS',
  GLOBAL_SUPPLIER_EDIT_ADMIN_FIELDS: 'GLOBAL_SUPPLIER_EDIT_ADMIN_FIELDS',
  PATTERN_VIEW_ADMIN_FIELDS: 'PATTERN_VIEW_ADMIN_FIELDS',
  PATTERN_EDIT_ADMIN_FIELDS: 'PATTERN_EDIT_ADMIN_FIELDS',
  PATTERN_RUN_ADMIN_ACTIONS: 'PATTERN_RUN_ADMIN_ACTIONS',
  INBOX_ITEM_OBJECTS_VIEW_CUSTOMER_FIELDS: 'INBOX_ITEM_OBJECTS_VIEW_CUSTOMER_FIELDS',
  INBOX_ITEM_OBJECTS_VIEW_ADMIN_FIELDS: 'INBOX_ITEM_OBJECTS_VIEW_ADMIN_FIELDS',
  INBOX_ITEM_OBJECTS_EDIT_ADMIN_FIELDS: 'INBOX_ITEM_OBJECTS_EDIT_ADMIN_FIELDS',
  INBOX_ITEM_OBJECTS_SEND_EMAIL: 'INBOX_ITEM_OBJECTS_SEND_EMAIL', // SYSTEM_ADMINS don't have this access
  INBOX_ITEM_OBJECTS_RUN_CUSTOMER_ACTIONS: 'INBOX_ITEM_OBJECTS_RUN_CUSTOMER_ACTIONS',
  INBOX_ITEM_OBJECTS_RUN_ADMIN_ACTIONS: 'INBOX_ITEM_OBJECTS_RUN_ADMIN_ACTIONS',
  DOC_OBJECTS_VIEW_CUSTOMER_FIELDS: 'DOC_OBJECTS_VIEW_CUSTOMER_FIELDS',
  DOC_OBJECTS_VIEW_ADMIN_FIELDS: 'DOC_OBJECTS_VIEW_ADMIN_FIELDS',
  DOC_OBJECTS_EDIT_ADMIN_FIELDS: 'DOC_OBJECTS_EDIT_ADMIN_FIELDS',
  DOC_OBJECTS_DELETE: 'DOC_OBJECTS_DELETE',
  DOC_OBJECTS_APPROVE: 'DOC_OBJECTS_APPROVE', // SYSTEM_ADMINS do not have this access
  DOC_OBJECTS_RUN_CUSTOMER_ACTIONS: 'DOC_OBJECTS_RUN_CUSTOMER_ACTIONS',
  DOC_OBJECTS_RUN_ADMIN_ACTIONS: 'DOC_OBJECTS_RUN_ADMIN_ACTIONS',
  STORED_FILE_VIEW_CUSTOMER_FIELDS: 'STORED_FILE_VIEW_CUSTOMER_FIELDS', // must be isTest=true
  STORED_FILE_VIEW_ADMIN_FIELDS: 'STORED_FILE_VIEW_ADMIN_FIELDS',
  USER_VIEW_CUSTOMER_FIELDS: 'USER_VIEW_CUSTOMER_FIELDS',
  USER_EDIT_CUSTOMER_FIELDS: 'USER_EDIT_CUSTOMER_FIELDS',
  USER_VIEW_ADMIN_FIELDS: 'USER_VIEW_ADMIN_FIELDS',
  USER_EDIT_ADMIN_FIELDS: 'USER_EDIT_ADMIN_FIELDS',
  RAW_POSTMARK_VIEW_ADMIN_FIELDS: 'RAW_POSTMARK_VIEW_ADMIN_FIELDS',
  RAW_POSTMARK_EDIT_ADMIN_FIELDS: 'RAW_POSTMARK_EDIT_ADMIN_FIELDS',
  RAW_POSTMARK_RUN_ADMIN_ACTIONS: 'RAW_POSTMARK_RUN_ADMIN_ACTIONS',
  LOGS_VIEW_ADMIN: 'LOGS_VIEW_ADMIN',
  LOGS_VIEW_CUSTOMER: 'LOGS_VIEW_CUSTOMER'
};
